# Generated by Django 4.2.7 on 2025-10-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Görsel')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Kategori Görseli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Alt Başlık')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Görsel')),
                ('primary_button_text', models.CharField(max_length=100, verbose_name='Birincil Buton Metni')),
                ('primary_button_url', models.CharField(max_length=200, verbose_name='Birincil Buton URL')),
                ('secondary_button_text', models.CharField(max_length=100, verbose_name='İkincil Buton Metni')),
                ('secondary_button_url', models.CharField(max_length=200, verbose_name='İkincil Buton URL')),
                ('tag_text', models.CharField(blank=True, max_length=100, verbose_name='Etiket Metni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kahraman Bölümü',
                'verbose_name_plural': 'Kahraman Bölümleri',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='promos/', verbose_name='Görsel')),
                ('button_text', models.CharField(max_length=100, verbose_name='Buton Metni')),
                ('button_url', models.CharField(max_length=200, verbose_name='Buton URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promosyon Bölümü',
                'verbose_name_plural': 'Promosyon Bölümleri',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='İhsan At Ekipmanları', max_length=100, verbose_name='Site Adı')),
                ('site_description', models.TextField(default='Pistten ahıra, tüm ekipman tek yerde.', verbose_name='Site Açıklaması')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('email', models.EmailField(default='destek@ihsan.tack', max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(default='0(850) xxx xx xx', max_length=20, verbose_name='Telefon')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('trust_message_1', models.CharField(default='Hızlı kargo', max_length=100, verbose_name='Güven Mesajı 1')),
                ('trust_message_2', models.CharField(default='30 gün iade', max_length=100, verbose_name='Güven Mesajı 2')),
                ('trust_message_3', models.CharField(default='Güvenli ödeme', max_length=100, verbose_name='Güven Mesajı 3')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kısa Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Eski Fiyat')),
                ('stock_status', models.CharField(choices=[('in_stock', 'Stokta'), ('limited', 'Sınırlı'), ('pre_order', 'Ön Sipariş'), ('out_of_stock', 'Stokta Yok')], default='in_stock', max_length=20, verbose_name='Stok Durumu')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Ana Görsel')),
                ('image_2', models.ImageField(blank=True, upload_to='products/', verbose_name='İkinci Görsel')),
                ('image_3', models.ImageField(blank=True, upload_to='products/', verbose_name='Üçüncü Görsel')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Ağırlık')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Boyutlar')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Malzeme')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Beden')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yeni Ürün')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
