# Generated by Django 4.2.7 on 2025-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('topic', models.CharField(help_text='Örn: Kalite ve Güven', max_length=100, verbose_name='Konu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('model_file', models.FileField(help_text='GLB formatında 3D model dosyası (maksimum 100MB)', upload_to='showcase/', verbose_name='3D Model Dosyası (GLB)')),
                ('button_text', models.CharField(default='KEŞFET', max_length=100, verbose_name='Buton Metni')),
                ('button_url', models.CharField(default='/', max_length=200, verbose_name='Buton URL')),
                ('badge_text', models.CharField(help_text='Örn: KALİTE GÜVENCE', max_length=100, verbose_name='Rozet Metni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showcase 3D Model',
                'verbose_name_plural': 'Showcase 3D Modelleri',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
