# Generated by Django 4.2.7 on 2025-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_showcasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasemodel',
            name='model_url',
            field=models.URLField(blank=True, help_text="Cloudflare R2 veya başka bir CDN'den GLB dosyasının URL'i (örnek: https://pub-xxx.r2.dev/showcase/model.glb)", verbose_name='3D Model URL (Cloudflare R2 vb.)'),
        ),
        migrations.AlterField(
            model_name='showcasemodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, help_text='VEYA GLB formatında 3D model dosyası yükleyin (maksimum 100MB). URL varsa bu alanı boş bırakabilirsiniz.', upload_to='showcase/', verbose_name='3D Model Dosyası (GLB) - Lokal Yükleme'),
        ),
    ]
