# Generated by Django 4.2.7 on 2025-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_showcasemodel_model_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasemodel',
            name='sketchfab_model_id',
            field=models.CharField(blank=True, help_text="Sketchfab model ID'si (örnek: 07882e7524534be984ae3e7faca25517). Sketchfab kullanmak için bu alanı doldurun.", max_length=100, verbose_name='Sketchfab Model ID'),
        ),
    ]
