# Generated by Django 4.2.7 on 2025-11-01 10:51

from django.db import migrations, models


def set_default_sketchfab_id(apps, schema_editor):
    """Boş sketchfab_model_id olan kayıtlar için geçici ID ata ve devre dışı bırak"""
    ShowcaseModel = apps.get_model('core', 'ShowcaseModel')
    empty_models = ShowcaseModel.objects.filter(sketchfab_model_id='')
    for model in empty_models:
        model.sketchfab_model_id = 'PLACEHOLDER_ID_NEEDS_UPDATE'
        model.is_active = False  # Geçersiz olanları gizle
        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_sketchfab_model_id'),
    ]

    operations = [
        migrations.RunPython(set_default_sketchfab_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='showcasemodel',
            name='sketchfab_model_id',
            field=models.CharField(help_text="Sketchfab model ID'si ZORUNLUDUR (örnek: 07882e7524534be984ae3e7faca25517). Sadece Model ID'yi veya tam embed URL'yi girebilirsiniz.", max_length=100, verbose_name='Sketchfab Model ID'),
        ),
    ]
