# Generated by Django 4.2.7 on 2025-11-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_showcasemodel_sketchfab_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasemodel',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='showcasemodel',
            name='model_url',
        ),
    ]
